### ISSUE TITLE
Map authors can now directly download their maps from oc.tc/maps.  Please update the ones here!

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [CoWinkKeyDinkInc/CardinalPGM-Maps#12]
Here's proof.

![Proof](https://i.imgur.com/dfPyfQT.png)

**Comment by CoWinkKeyDinkInc** [comment]
@matic0basle 
@Prodigy4532 
@TiTo-418 
@Mikeg542

If you could get them, that would be great!

**Comment by ghost** [comment]
@CoWinkKeyDinkInc We don't have perms lol

**Comment by CoWinkKeyDinkInc** [comment]
@TiTo-418 If you are the author of a map, you can download that map.  I did not say that anyone can download them all.

**Comment by Prodigy4532** [comment]
I dont have maps in ocn

**Comment by CoWinkKeyDinkInc** [comment]
@Prodigy4532 It's okay.
