### ISSUE TITLE
Table Block Issues

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [CoWinkKeyDinkInc/CardinalPGM-Maps#13]
- Guy spawned in a block.
- Sign to Iron building.
- ~~Iron didn't regen.~~  Block regeneration isn't supported in CardinalPGM
- Players can mine their own monument.
- Players get stuck in air when they try to go inside their own monument.
- Some players were able to enter their own wool room.
- Obsidian went into players inventory.
- People could place blocks in areas they shouldn't be allowed to like:
  - inside the hour glass
  - on the teleport platform
  - inside the wool room
- People could break the teleport platform

[Table Block Test Video](https://www.youtube.com/watch?v=l9WaX5ny6Yo)
[How Table Block works](https://www.youtube.com/watch?v=p0xg7DMn-uo)

**Comment by Lmmb74** [comment]
Hey, check my pull :DDD

**Comment by Lmmb74** [comment]
Welp, close this pls

**Comment by CoWinkKeyDinkInc** [comment]
Fixed in #21, #22 and #25
