### ISSUE TITLE
A team gear map is twice in the repo

### ISSUE THREAD

**Issue by Pablete1234** [CoWinkKeyDinkInc/CardinalPGM-Maps#18]
`KotH/A team gear map/`
`DTC/Dry DTC/`

there is an xml with map name "A team gear map" in each of the folders

**Comment by CoWinkKeyDinkInc** [comment]
An XML file was not created for this map, thus I forgot to change it when creating starter XML files.

Fixed in 10d81b80d02a684222c467cd900f35aa4214aedf
